version: "3.7"

services:
  parse:
    image: parseplatform/parse-server:4.2.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    env_file:
      - ../.env
    environment:
        PARSE_SERVER_APPLICATION_ID: geminis
        PARSE_SERVER_DATABASE_URI: mongodb://parse:gema@mongo/geminis
        PARSE_SERVER_URL: https://parse.geminis.dev/parse
        PARSE_SERVER_MOUNT_GRAPHQL: "true"
    labels:
        gema.service: parse
        gema.auth: 0
        gema.port: 1337
        gema.subdomain: parse
        gema.cors: "yes"
    networks:
      - gema
    volumes:
      - cloud-code:/parse-server/cloud
      - config:/parse-server/config

  parse-dash:
    image: parseplatform/parse-dashboard:2.0.5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    env_file:
      - ../.env
    environment:
      PARSE_DASHBOARD_SERVER_URL: https://parse.geminis.dev/parse
      PARSE_DASHBOARD_GRAPHQL_URL: https://parse.geminis.dev/graphql
      PARSE_DASHBOARD_APP_ID: geminis
      PARSE_DASHBOARD_USER_ID: gema
      PARSE_DASHBOARD_TRUST_PROXY: 1
    labels:
        gema.service: parse-dash
        gema.auth: 0
        gema.port: 4040
        gema.subdomain: parsed
    networks:
      - gema

  mongo:
    image: mongo:4.2.6
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    environment:
        MONGO_INITDB_ROOT_USERNAME: gema
        MONGO_INITDB_ROOT_PASSWORD: gema
        MONGO_INITDB_DATABASE: geminis
    networks:
      - gema
    volumes:
      - mongodb:/data/db

networks:
  gema:
    external: true

volumes:
  mongodb:
  cloud-code:
  config:
