version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - gema
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    networks:
        - gema

  grafana:
    image: grafana/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - gema
    volumes:
      - grafana_data:/var/lib/grafana

  postgres:
    image: postgres:alpine
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "5432:5432"
    networks:
      - gema
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - gema
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./certs/domain.crt:/certs/server.cert
      - ./certs/domain.key:/certs/server.key

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - gema
    volumes:
      - redis_data:/data

  # kafka:
  #
  # elasticsearch:
  #
  # logstash:
  #
  # kibana:

networks:
  gema:
    external: true

volumes:
  grafana_data:
  pgadmin_data:
  postgres_data:
  redis_data:
