version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema_gema
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth:/auth
      - ./certs:/certs
      - gema_nginx_logs:/var/log/nginx/
      - nginx_static:/usr/share/nginx/html
      - nginx_sockets:/sockets

networks:
  gema_gema:
    external: true

volumes:
  nginx_static:
  nginx_sockets:
  gema_nginx_logs:
    external: true
