version: "3.7"

services:
  portainer-agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
      - gema_gema
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.portainer-agent:9001 --ssl --sslcert /certs/domain.crt --sslkey /certs/domain.key
    networks:
      - portainer
      - gema_gema
    volumes:
      - portainer_data:/data
      - ./certs:/certs
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  registry:
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_REDIS_ADDR: redis:6379
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - gema_gema
    volumes:
      - registry_data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth

volumes:
  portainer_data:
  registry_data:
  redis_registry_data:

networks:
  portainer:
    driver: overlay
    attachable: true
  gema_gema:
    external: true
