version: "3.7"

services:
  test:
    image: jwilder/whoami
    labels:
      gema.service: test
      gema.auth: 1
      gema.port: 8000
      gema.subdomain: test
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
        - gema


networks:
  gema:
    external: true
