version: "3.7"

services:
  chat:
    image: mattermost/mattermost-team-edition:5.8.0
    env_file:
      - ../.env
    environment:
      DB_HOST: postgres
      MM_DBNAME: gema_mm
    labels:
      gema.service: chat
      gema.auth: 0
      gema.port: 8000
      gema.subdomain: chat
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    healthcheck: 
      test: curl --fail http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
        - gema
    volumes:
      - config:/mattermost/config:rw
      - data:/mattermost/data:rw
      - logs:/mattermost/logs:rw
      - plugins:/mattermost/plugins:rw
      - /etc/localtime:/etc/localtime:ro

volumes:
  config:
  data:
  logs:
  plugins:

networks:
  gema:
    external: true

