version: "3.7"

services:
  backup:
    image: localhost:5000/gema/backup
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: wget --quiet --tries=1 --spider 127.0.0.1/ || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
        - gema

networks:
  gema:
    external: true
