version: "3.7"

services:
  sentry:
    image: sentry
    labels:
      gema.service: sentry
      gema.auth: 1
      gema.port: 9000
      gema.subdomain: sentry
    env_file:
      - ../.env
      - sentry.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    volumes:
      - data:/var/lib/sentry/files
    networks:
      - gema

  sentry-cron:
    image: sentry
    command: ["run", "cron"]
    env_file:
      - ../.env
      - sentry.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema

  sentry-worker:
    image: sentry
    command: ["run", "worker"]
    env_file:
      - ../.env
      - sentry.env
    deploy:
      mode: global
    networks:
      - gema

  sentry-redis:
    image: redis:alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema
    volumes:
      - redis_data:/data

networks:
  gema:
    external: true

volumes:
  data:
  redis_data:
