version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../auth:/auth
      - ../certs:/certs
      - logs:/var/log/nginx/
      - static:/static

networks:
  gema:
    external: true

volumes:
  static:
  logs:
