version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    env_file:
      - ../.env
    environment:
      network.host: 0.0.0.0
      cluster.name: elastic
      node.name: elasticsearch
      discovery.seed_hosts: elasticsearch
      cluster.initial_master_nodes: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    env_file:
      - ../.env
    labels:
      gema.service: kibana
      gema.auth: 1
      gema.port: 5601
      gema.subdomain: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema
    volumes:
      - kibana_data:/usr/share/kibana/data

  # metricbeat:
  #   image: docker.elastic.co/beats/metricbeat:7.0.0
  #   volumes:
  #     - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
  #   networks:
  #     - gema
  #   env_file:
  #     - ../.env
  #   deploy:
  #     mode: global
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  #     placement:
  #       constraints: [node.labels.category == main]
  #   command: metricbeat -e -strict.perms=false

  # filebeat:
  #   user: root
  #   image: docker.elastic.co/beats/filebeat:7.0.0
  #   volumes:
  #     - nginx_logs:/var/log/nginx
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - /var/log/auth.log:/var/log/auth.log
  #     - /var/log/syslog:/var/log/syslog
  #   networks:
  #     - gema
  #   deploy:
  #     mode: global
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  #     placement:
  #       constraints: [node.labels.category == main]
  #   command: filebeat -e -strict.perms=false

  apm:
    image: docker.elastic.co/apm/apm-server:7.0.0
    networks:
      - gema
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    command: apm-server -e -strict.perms=false

networks:
  gema:
    external: true

volumes:
  elasticsearch_data:
  kibana_data:
  nginx_logs:
    external: true
