version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    hostname: "elasticsearch"
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - discovery.zen.minimum_master_nodes=1
      - cluster.name=elastic
      - node.name=elasticsearch
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - gema
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    env_file:
      - ../.env
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - gema
    volumes:
      - kibana_data:/usr/share/kibana/data

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.3.2
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    networks:
      - gema
    env_file:
      - ../.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.2
    volumes:
      - nginx_logs:/var/log/nginx
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log/auth.log:/var/log/auth.log
      - /var/log/syslog:/var/log/syslog
    networks:
      - gema
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  gema:
    external: true

volumes:
  elasticsearch_data:
  kibana_data:
  nginx_logs:
    external: true
