version: "3.7"

services:
  portainer-agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - gema
      - portainer
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  portainer:
    image: portainer/portainer
    labels:
      gema.service: portainer
      gema.auth: 1
      gema.port: 9000
      gema.subdomain: portainer
    command: --no-auth --tlsskipverify
    networks:
      - gema
      - portainer
    volumes:
      - portainer_data:/data
      # - ../certs:/certs --ssl --sslcert /certs/domain.crt --sslkey /certs/domain.key
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]

  registry:
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_REDIS_ADDR: redis:6379
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    ports:
    - 5000:5000
    networks:
      - gema
    volumes:
      - registry_data:/var/lib/registry
      - ../certs:/certs
      - ../auth:/auth

  registry-redis:
    image: redis:alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema
    volumes:
      - redis_data:/data

volumes:
  portainer_data:
  registry_data:
  redis_data:

networks:
  gema:
    external: true
  portainer:
    driver: overlay
    attachable: true
