version: "3.7"

services:
  agent:
    image: localhost:5000/gema/agent
    env_file:
      - ../.env
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    healthcheck:
      test: wget --quiet --tries=1 --spider 127.0.0.1:8080/gema/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
        - gema
    volumes:
      - /var/run/docker.sock:/docker.sock

networks:
  gema:
    external: true
