version: '2'

services:
  acmedns:
    image: joohoi/acme-dns:latest
    labels:
        gema.service: acme
        gema.auth: 0
        gema.port: 80
        gema.subdomain: acme
    deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
        placement:
          constraints: [node.labels.category == main]
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - gema
    volumes:
      - ./config:/etc/acme-dns:ro
      - data:/var/lib/acme-dns

networks:
    gema:
        external: true
      

volumes:
    data:
