version: "3.7"

services:
  postgres:
    image: postgres:10.5-alpine
    env_file:
      - ../.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../.env
    labels:
      gema.service: pgadmin
      gema.auth: 1
      gema.subdomain: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@geminis.io
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
      - gema
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  gema:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
